name: Lint

on:
  pull_request:

jobs:
  tests:
    name: Coding Standard
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          tools: ecs, cs2pr
          coverage: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run ecs check
        run: ecs check --ansi --output-format=checkstyle | cs2pr

# vim:ft=yaml:et:ts=2:sw=2
